# Generated by Django 5.0.6 on 2024-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_image', models.ImageField(upload_to='my_infoimage')),
                ('p_det', models.TextField()),
            ],
        ),
    ]
