# Generated by Django 5.0.6 on 2024-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_image', models.ImageField(upload_to='my_infoimage')),
                ('s_heading', models.CharField(max_length=50)),
                ('s_det', models.TextField()),
            ],
        ),
    ]
